# Generated by Django 4.2.6 on 2023-10-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact_orders_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
